//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendSMS.SendSms_V5 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.afe.ir/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.afe.ir/", ConfigurationName="SendSms_V5.BoxServiceSoap")]
    public interface BoxServiceSoap {
        
        // CODEGEN: Generating message contract since element name Username from namespace http://www.afe.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.afe.ir/SendMessage", ReplyAction="*")]
        SendSMS.SendSms_V5.SendMessageResponse SendMessage(SendSMS.SendSms_V5.SendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.afe.ir/SendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<SendSMS.SendSms_V5.SendMessageResponse> SendMessageAsync(SendSMS.SendSms_V5.SendMessageRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://www.afe.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.afe.ir/GetMessageStatus", ReplyAction="*")]
        SendSMS.SendSms_V5.GetMessageStatusResponse GetMessageStatus(SendSMS.SendSms_V5.GetMessageStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.afe.ir/GetMessageStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<SendSMS.SendSms_V5.GetMessageStatusResponse> GetMessageStatusAsync(SendSMS.SendSms_V5.GetMessageStatusRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://www.afe.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.afe.ir/GetMessagesStatus", ReplyAction="*")]
        SendSMS.SendSms_V5.GetMessagesStatusResponse GetMessagesStatus(SendSMS.SendSms_V5.GetMessagesStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.afe.ir/GetMessagesStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<SendSMS.SendSms_V5.GetMessagesStatusResponse> GetMessagesStatusAsync(SendSMS.SendSms_V5.GetMessagesStatusRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://www.afe.ir/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.afe.ir/GetRemainingCredit", ReplyAction="*")]
        SendSMS.SendSms_V5.GetRemainingCreditResponse GetRemainingCredit(SendSMS.SendSms_V5.GetRemainingCreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.afe.ir/GetRemainingCredit", ReplyAction="*")]
        System.Threading.Tasks.Task<SendSMS.SendSms_V5.GetRemainingCreditResponse> GetRemainingCreditAsync(SendSMS.SendSms_V5.GetRemainingCreditRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://www.afe.ir/", Order=0)]
        public SendSMS.SendSms_V5.SendMessageRequestBody Body;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(SendSMS.SendSms_V5.SendMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.afe.ir/")]
    public partial class SendMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Number;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public SendSMS.SendSms_V5.ArrayOfString Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Type;
        
        public SendMessageRequestBody() {
        }
        
        public SendMessageRequestBody(string Username, string Password, string Number, SendSMS.SendSms_V5.ArrayOfString Mobile, string Message, string Type) {
            this.Username = Username;
            this.Password = Password;
            this.Number = Number;
            this.Mobile = Mobile;
            this.Message = Message;
            this.Type = Type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://www.afe.ir/", Order=0)]
        public SendSMS.SendSms_V5.SendMessageResponseBody Body;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(SendSMS.SendSms_V5.SendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.afe.ir/")]
    public partial class SendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SendSMS.SendSms_V5.ArrayOfString SendMessageResult;
        
        public SendMessageResponseBody() {
        }
        
        public SendMessageResponseBody(SendSMS.SendSms_V5.ArrayOfString SendMessageResult) {
            this.SendMessageResult = SendMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageStatus", Namespace="http://www.afe.ir/", Order=0)]
        public SendSMS.SendSms_V5.GetMessageStatusRequestBody Body;
        
        public GetMessageStatusRequest() {
        }
        
        public GetMessageStatusRequest(SendSMS.SendSms_V5.GetMessageStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.afe.ir/")]
    public partial class GetMessageStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SmsID;
        
        public GetMessageStatusRequestBody() {
        }
        
        public GetMessageStatusRequestBody(string Username, string Password, string SmsID) {
            this.Username = Username;
            this.Password = Password;
            this.SmsID = SmsID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageStatusResponse", Namespace="http://www.afe.ir/", Order=0)]
        public SendSMS.SendSms_V5.GetMessageStatusResponseBody Body;
        
        public GetMessageStatusResponse() {
        }
        
        public GetMessageStatusResponse(SendSMS.SendSms_V5.GetMessageStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.afe.ir/")]
    public partial class GetMessageStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMessageStatusResult;
        
        public GetMessageStatusResponseBody() {
        }
        
        public GetMessageStatusResponseBody(string GetMessageStatusResult) {
            this.GetMessageStatusResult = GetMessageStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessagesStatus", Namespace="http://www.afe.ir/", Order=0)]
        public SendSMS.SendSms_V5.GetMessagesStatusRequestBody Body;
        
        public GetMessagesStatusRequest() {
        }
        
        public GetMessagesStatusRequest(SendSMS.SendSms_V5.GetMessagesStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.afe.ir/")]
    public partial class GetMessagesStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public SendSMS.SendSms_V5.ArrayOfString SmsID;
        
        public GetMessagesStatusRequestBody() {
        }
        
        public GetMessagesStatusRequestBody(string Username, string Password, SendSMS.SendSms_V5.ArrayOfString SmsID) {
            this.Username = Username;
            this.Password = Password;
            this.SmsID = SmsID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessagesStatusResponse", Namespace="http://www.afe.ir/", Order=0)]
        public SendSMS.SendSms_V5.GetMessagesStatusResponseBody Body;
        
        public GetMessagesStatusResponse() {
        }
        
        public GetMessagesStatusResponse(SendSMS.SendSms_V5.GetMessagesStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.afe.ir/")]
    public partial class GetMessagesStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SendSMS.SendSms_V5.ArrayOfString GetMessagesStatusResult;
        
        public GetMessagesStatusResponseBody() {
        }
        
        public GetMessagesStatusResponseBody(SendSMS.SendSms_V5.ArrayOfString GetMessagesStatusResult) {
            this.GetMessagesStatusResult = GetMessagesStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRemainingCreditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRemainingCredit", Namespace="http://www.afe.ir/", Order=0)]
        public SendSMS.SendSms_V5.GetRemainingCreditRequestBody Body;
        
        public GetRemainingCreditRequest() {
        }
        
        public GetRemainingCreditRequest(SendSMS.SendSms_V5.GetRemainingCreditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.afe.ir/")]
    public partial class GetRemainingCreditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public GetRemainingCreditRequestBody() {
        }
        
        public GetRemainingCreditRequestBody(string Username, string Password) {
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRemainingCreditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRemainingCreditResponse", Namespace="http://www.afe.ir/", Order=0)]
        public SendSMS.SendSms_V5.GetRemainingCreditResponseBody Body;
        
        public GetRemainingCreditResponse() {
        }
        
        public GetRemainingCreditResponse(SendSMS.SendSms_V5.GetRemainingCreditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.afe.ir/")]
    public partial class GetRemainingCreditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetRemainingCreditResult;
        
        public GetRemainingCreditResponseBody() {
        }
        
        public GetRemainingCreditResponseBody(string GetRemainingCreditResult) {
            this.GetRemainingCreditResult = GetRemainingCreditResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BoxServiceSoapChannel : SendSMS.SendSms_V5.BoxServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BoxServiceSoapClient : System.ServiceModel.ClientBase<SendSMS.SendSms_V5.BoxServiceSoap>, SendSMS.SendSms_V5.BoxServiceSoap {
        
        public BoxServiceSoapClient() {
        }
        
        public BoxServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BoxServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BoxServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BoxServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendSMS.SendSms_V5.SendMessageResponse SendSMS.SendSms_V5.BoxServiceSoap.SendMessage(SendSMS.SendSms_V5.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public SendSMS.SendSms_V5.ArrayOfString SendMessage(string Username, string Password, string Number, SendSMS.SendSms_V5.ArrayOfString Mobile, string Message, string Type) {
            SendSMS.SendSms_V5.SendMessageRequest inValue = new SendSMS.SendSms_V5.SendMessageRequest();
            inValue.Body = new SendSMS.SendSms_V5.SendMessageRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.Number = Number;
            inValue.Body.Mobile = Mobile;
            inValue.Body.Message = Message;
            inValue.Body.Type = Type;
            SendSMS.SendSms_V5.SendMessageResponse retVal = ((SendSMS.SendSms_V5.BoxServiceSoap)(this)).SendMessage(inValue);
            return retVal.Body.SendMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendSMS.SendSms_V5.SendMessageResponse> SendSMS.SendSms_V5.BoxServiceSoap.SendMessageAsync(SendSMS.SendSms_V5.SendMessageRequest request) {
            return base.Channel.SendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendSMS.SendSms_V5.SendMessageResponse> SendMessageAsync(string Username, string Password, string Number, SendSMS.SendSms_V5.ArrayOfString Mobile, string Message, string Type) {
            SendSMS.SendSms_V5.SendMessageRequest inValue = new SendSMS.SendSms_V5.SendMessageRequest();
            inValue.Body = new SendSMS.SendSms_V5.SendMessageRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.Number = Number;
            inValue.Body.Mobile = Mobile;
            inValue.Body.Message = Message;
            inValue.Body.Type = Type;
            return ((SendSMS.SendSms_V5.BoxServiceSoap)(this)).SendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendSMS.SendSms_V5.GetMessageStatusResponse SendSMS.SendSms_V5.BoxServiceSoap.GetMessageStatus(SendSMS.SendSms_V5.GetMessageStatusRequest request) {
            return base.Channel.GetMessageStatus(request);
        }
        
        public string GetMessageStatus(string Username, string Password, string SmsID) {
            SendSMS.SendSms_V5.GetMessageStatusRequest inValue = new SendSMS.SendSms_V5.GetMessageStatusRequest();
            inValue.Body = new SendSMS.SendSms_V5.GetMessageStatusRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.SmsID = SmsID;
            SendSMS.SendSms_V5.GetMessageStatusResponse retVal = ((SendSMS.SendSms_V5.BoxServiceSoap)(this)).GetMessageStatus(inValue);
            return retVal.Body.GetMessageStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendSMS.SendSms_V5.GetMessageStatusResponse> SendSMS.SendSms_V5.BoxServiceSoap.GetMessageStatusAsync(SendSMS.SendSms_V5.GetMessageStatusRequest request) {
            return base.Channel.GetMessageStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendSMS.SendSms_V5.GetMessageStatusResponse> GetMessageStatusAsync(string Username, string Password, string SmsID) {
            SendSMS.SendSms_V5.GetMessageStatusRequest inValue = new SendSMS.SendSms_V5.GetMessageStatusRequest();
            inValue.Body = new SendSMS.SendSms_V5.GetMessageStatusRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.SmsID = SmsID;
            return ((SendSMS.SendSms_V5.BoxServiceSoap)(this)).GetMessageStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendSMS.SendSms_V5.GetMessagesStatusResponse SendSMS.SendSms_V5.BoxServiceSoap.GetMessagesStatus(SendSMS.SendSms_V5.GetMessagesStatusRequest request) {
            return base.Channel.GetMessagesStatus(request);
        }
        
        public SendSMS.SendSms_V5.ArrayOfString GetMessagesStatus(string Username, string Password, SendSMS.SendSms_V5.ArrayOfString SmsID) {
            SendSMS.SendSms_V5.GetMessagesStatusRequest inValue = new SendSMS.SendSms_V5.GetMessagesStatusRequest();
            inValue.Body = new SendSMS.SendSms_V5.GetMessagesStatusRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.SmsID = SmsID;
            SendSMS.SendSms_V5.GetMessagesStatusResponse retVal = ((SendSMS.SendSms_V5.BoxServiceSoap)(this)).GetMessagesStatus(inValue);
            return retVal.Body.GetMessagesStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendSMS.SendSms_V5.GetMessagesStatusResponse> SendSMS.SendSms_V5.BoxServiceSoap.GetMessagesStatusAsync(SendSMS.SendSms_V5.GetMessagesStatusRequest request) {
            return base.Channel.GetMessagesStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendSMS.SendSms_V5.GetMessagesStatusResponse> GetMessagesStatusAsync(string Username, string Password, SendSMS.SendSms_V5.ArrayOfString SmsID) {
            SendSMS.SendSms_V5.GetMessagesStatusRequest inValue = new SendSMS.SendSms_V5.GetMessagesStatusRequest();
            inValue.Body = new SendSMS.SendSms_V5.GetMessagesStatusRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.SmsID = SmsID;
            return ((SendSMS.SendSms_V5.BoxServiceSoap)(this)).GetMessagesStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendSMS.SendSms_V5.GetRemainingCreditResponse SendSMS.SendSms_V5.BoxServiceSoap.GetRemainingCredit(SendSMS.SendSms_V5.GetRemainingCreditRequest request) {
            return base.Channel.GetRemainingCredit(request);
        }
        
        public string GetRemainingCredit(string Username, string Password) {
            SendSMS.SendSms_V5.GetRemainingCreditRequest inValue = new SendSMS.SendSms_V5.GetRemainingCreditRequest();
            inValue.Body = new SendSMS.SendSms_V5.GetRemainingCreditRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            SendSMS.SendSms_V5.GetRemainingCreditResponse retVal = ((SendSMS.SendSms_V5.BoxServiceSoap)(this)).GetRemainingCredit(inValue);
            return retVal.Body.GetRemainingCreditResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendSMS.SendSms_V5.GetRemainingCreditResponse> SendSMS.SendSms_V5.BoxServiceSoap.GetRemainingCreditAsync(SendSMS.SendSms_V5.GetRemainingCreditRequest request) {
            return base.Channel.GetRemainingCreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendSMS.SendSms_V5.GetRemainingCreditResponse> GetRemainingCreditAsync(string Username, string Password) {
            SendSMS.SendSms_V5.GetRemainingCreditRequest inValue = new SendSMS.SendSms_V5.GetRemainingCreditRequest();
            inValue.Body = new SendSMS.SendSms_V5.GetRemainingCreditRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            return ((SendSMS.SendSms_V5.BoxServiceSoap)(this)).GetRemainingCreditAsync(inValue);
        }
    }
}
