//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendSMS.GetSms {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageReceived", Namespace="http://www.AsreFaraErtebat.com/")]
    [System.SerializableAttribute()]
    public partial class MessageReceived : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToField;
        
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        private int CharCountField;
        
        private bool IsUnicodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string From {
            get {
                return this.FromField;
            }
            set {
                if ((object.ReferenceEquals(this.FromField, value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string To {
            get {
                return this.ToField;
            }
            set {
                if ((object.ReferenceEquals(this.ToField, value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int CharCount {
            get {
                return this.CharCountField;
            }
            set {
                if ((this.CharCountField.Equals(value) != true)) {
                    this.CharCountField = value;
                    this.RaisePropertyChanged("CharCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool IsUnicode {
            get {
                return this.IsUnicodeField;
            }
            set {
                if ((this.IsUnicodeField.Equals(value) != true)) {
                    this.IsUnicodeField = value;
                    this.RaisePropertyChanged("IsUnicode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.AsreFaraErtebat.com/", ConfigurationName="GetSms.InboxServiceSoap")]
    public interface InboxServiceSoap {
        
        // CODEGEN: Generating message contract since element name Username from namespace http://www.AsreFaraErtebat.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.AsreFaraErtebat.com/Get", ReplyAction="*")]
        SendSMS.GetSms.GetResponse Get(SendSMS.GetSms.GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.AsreFaraErtebat.com/Get", ReplyAction="*")]
        System.Threading.Tasks.Task<SendSMS.GetSms.GetResponse> GetAsync(SendSMS.GetSms.GetRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://www.AsreFaraErtebat.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.AsreFaraErtebat.com/GetNext", ReplyAction="*")]
        SendSMS.GetSms.GetNextResponse GetNext(SendSMS.GetSms.GetNextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.AsreFaraErtebat.com/GetNext", ReplyAction="*")]
        System.Threading.Tasks.Task<SendSMS.GetSms.GetNextResponse> GetNextAsync(SendSMS.GetSms.GetNextRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://www.AsreFaraErtebat.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.AsreFaraErtebat.com/GetPerior", ReplyAction="*")]
        SendSMS.GetSms.GetPeriorResponse GetPerior(SendSMS.GetSms.GetPeriorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.AsreFaraErtebat.com/GetPerior", ReplyAction="*")]
        System.Threading.Tasks.Task<SendSMS.GetSms.GetPeriorResponse> GetPeriorAsync(SendSMS.GetSms.GetPeriorRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://www.AsreFaraErtebat.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.AsreFaraErtebat.com/GetFirst", ReplyAction="*")]
        SendSMS.GetSms.GetFirstResponse GetFirst(SendSMS.GetSms.GetFirstRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.AsreFaraErtebat.com/GetFirst", ReplyAction="*")]
        System.Threading.Tasks.Task<SendSMS.GetSms.GetFirstResponse> GetFirstAsync(SendSMS.GetSms.GetFirstRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://www.AsreFaraErtebat.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.AsreFaraErtebat.com/GetLast", ReplyAction="*")]
        SendSMS.GetSms.GetLastResponse GetLast(SendSMS.GetSms.GetLastRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.AsreFaraErtebat.com/GetLast", ReplyAction="*")]
        System.Threading.Tasks.Task<SendSMS.GetSms.GetLastResponse> GetLastAsync(SendSMS.GetSms.GetLastRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://www.AsreFaraErtebat.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.AsreFaraErtebat.com/GetCount", ReplyAction="*")]
        SendSMS.GetSms.GetCountResponse GetCount(SendSMS.GetSms.GetCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.AsreFaraErtebat.com/GetCount", ReplyAction="*")]
        System.Threading.Tasks.Task<SendSMS.GetSms.GetCountResponse> GetCountAsync(SendSMS.GetSms.GetCountRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://www.AsreFaraErtebat.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.AsreFaraErtebat.com/List", ReplyAction="*")]
        SendSMS.GetSms.ListResponse List(SendSMS.GetSms.ListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.AsreFaraErtebat.com/List", ReplyAction="*")]
        System.Threading.Tasks.Task<SendSMS.GetSms.ListResponse> ListAsync(SendSMS.GetSms.ListRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://www.AsreFaraErtebat.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.AsreFaraErtebat.com/GetForwardUrl", ReplyAction="*")]
        SendSMS.GetSms.GetForwardUrlResponse GetForwardUrl(SendSMS.GetSms.GetForwardUrlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.AsreFaraErtebat.com/GetForwardUrl", ReplyAction="*")]
        System.Threading.Tasks.Task<SendSMS.GetSms.GetForwardUrlResponse> GetForwardUrlAsync(SendSMS.GetSms.GetForwardUrlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get", Namespace="http://www.AsreFaraErtebat.com/", Order=0)]
        public SendSMS.GetSms.GetRequestBody Body;
        
        public GetRequest() {
        }
        
        public GetRequest(SendSMS.GetSms.GetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.AsreFaraErtebat.com/")]
    public partial class GetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int ID;
        
        public GetRequestBody() {
        }
        
        public GetRequestBody(string Username, string Password, int ID) {
            this.Username = Username;
            this.Password = Password;
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponse", Namespace="http://www.AsreFaraErtebat.com/", Order=0)]
        public SendSMS.GetSms.GetResponseBody Body;
        
        public GetResponse() {
        }
        
        public GetResponse(SendSMS.GetSms.GetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.AsreFaraErtebat.com/")]
    public partial class GetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SendSMS.GetSms.MessageReceived GetResult;
        
        public GetResponseBody() {
        }
        
        public GetResponseBody(SendSMS.GetSms.MessageReceived GetResult) {
            this.GetResult = GetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNext", Namespace="http://www.AsreFaraErtebat.com/", Order=0)]
        public SendSMS.GetSms.GetNextRequestBody Body;
        
        public GetNextRequest() {
        }
        
        public GetNextRequest(SendSMS.GetSms.GetNextRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.AsreFaraErtebat.com/")]
    public partial class GetNextRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string To;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int ID;
        
        public GetNextRequestBody() {
        }
        
        public GetNextRequestBody(string Username, string Password, string To, int ID) {
            this.Username = Username;
            this.Password = Password;
            this.To = To;
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNextResponse", Namespace="http://www.AsreFaraErtebat.com/", Order=0)]
        public SendSMS.GetSms.GetNextResponseBody Body;
        
        public GetNextResponse() {
        }
        
        public GetNextResponse(SendSMS.GetSms.GetNextResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.AsreFaraErtebat.com/")]
    public partial class GetNextResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SendSMS.GetSms.MessageReceived GetNextResult;
        
        public GetNextResponseBody() {
        }
        
        public GetNextResponseBody(SendSMS.GetSms.MessageReceived GetNextResult) {
            this.GetNextResult = GetNextResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPeriorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPerior", Namespace="http://www.AsreFaraErtebat.com/", Order=0)]
        public SendSMS.GetSms.GetPeriorRequestBody Body;
        
        public GetPeriorRequest() {
        }
        
        public GetPeriorRequest(SendSMS.GetSms.GetPeriorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.AsreFaraErtebat.com/")]
    public partial class GetPeriorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string To;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int ID;
        
        public GetPeriorRequestBody() {
        }
        
        public GetPeriorRequestBody(string Username, string Password, string To, int ID) {
            this.Username = Username;
            this.Password = Password;
            this.To = To;
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPeriorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPeriorResponse", Namespace="http://www.AsreFaraErtebat.com/", Order=0)]
        public SendSMS.GetSms.GetPeriorResponseBody Body;
        
        public GetPeriorResponse() {
        }
        
        public GetPeriorResponse(SendSMS.GetSms.GetPeriorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.AsreFaraErtebat.com/")]
    public partial class GetPeriorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SendSMS.GetSms.MessageReceived GetPeriorResult;
        
        public GetPeriorResponseBody() {
        }
        
        public GetPeriorResponseBody(SendSMS.GetSms.MessageReceived GetPeriorResult) {
            this.GetPeriorResult = GetPeriorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFirstRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFirst", Namespace="http://www.AsreFaraErtebat.com/", Order=0)]
        public SendSMS.GetSms.GetFirstRequestBody Body;
        
        public GetFirstRequest() {
        }
        
        public GetFirstRequest(SendSMS.GetSms.GetFirstRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.AsreFaraErtebat.com/")]
    public partial class GetFirstRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string To;
        
        public GetFirstRequestBody() {
        }
        
        public GetFirstRequestBody(string Username, string Password, string To) {
            this.Username = Username;
            this.Password = Password;
            this.To = To;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFirstResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFirstResponse", Namespace="http://www.AsreFaraErtebat.com/", Order=0)]
        public SendSMS.GetSms.GetFirstResponseBody Body;
        
        public GetFirstResponse() {
        }
        
        public GetFirstResponse(SendSMS.GetSms.GetFirstResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.AsreFaraErtebat.com/")]
    public partial class GetFirstResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SendSMS.GetSms.MessageReceived GetFirstResult;
        
        public GetFirstResponseBody() {
        }
        
        public GetFirstResponseBody(SendSMS.GetSms.MessageReceived GetFirstResult) {
            this.GetFirstResult = GetFirstResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLast", Namespace="http://www.AsreFaraErtebat.com/", Order=0)]
        public SendSMS.GetSms.GetLastRequestBody Body;
        
        public GetLastRequest() {
        }
        
        public GetLastRequest(SendSMS.GetSms.GetLastRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.AsreFaraErtebat.com/")]
    public partial class GetLastRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string To;
        
        public GetLastRequestBody() {
        }
        
        public GetLastRequestBody(string Username, string Password, string To) {
            this.Username = Username;
            this.Password = Password;
            this.To = To;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastResponse", Namespace="http://www.AsreFaraErtebat.com/", Order=0)]
        public SendSMS.GetSms.GetLastResponseBody Body;
        
        public GetLastResponse() {
        }
        
        public GetLastResponse(SendSMS.GetSms.GetLastResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.AsreFaraErtebat.com/")]
    public partial class GetLastResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SendSMS.GetSms.MessageReceived GetLastResult;
        
        public GetLastResponseBody() {
        }
        
        public GetLastResponseBody(SendSMS.GetSms.MessageReceived GetLastResult) {
            this.GetLastResult = GetLastResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCount", Namespace="http://www.AsreFaraErtebat.com/", Order=0)]
        public SendSMS.GetSms.GetCountRequestBody Body;
        
        public GetCountRequest() {
        }
        
        public GetCountRequest(SendSMS.GetSms.GetCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.AsreFaraErtebat.com/")]
    public partial class GetCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string To;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int ID;
        
        public GetCountRequestBody() {
        }
        
        public GetCountRequestBody(string Username, string Password, string To, int ID) {
            this.Username = Username;
            this.Password = Password;
            this.To = To;
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountResponse", Namespace="http://www.AsreFaraErtebat.com/", Order=0)]
        public SendSMS.GetSms.GetCountResponseBody Body;
        
        public GetCountResponse() {
        }
        
        public GetCountResponse(SendSMS.GetSms.GetCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.AsreFaraErtebat.com/")]
    public partial class GetCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetCountResult;
        
        public GetCountResponseBody() {
        }
        
        public GetCountResponseBody(int GetCountResult) {
            this.GetCountResult = GetCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="List", Namespace="http://www.AsreFaraErtebat.com/", Order=0)]
        public SendSMS.GetSms.ListRequestBody Body;
        
        public ListRequest() {
        }
        
        public ListRequest(SendSMS.GetSms.ListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.AsreFaraErtebat.com/")]
    public partial class ListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string To;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Count;
        
        public ListRequestBody() {
        }
        
        public ListRequestBody(string Username, string Password, string To, int ID, int Count) {
            this.Username = Username;
            this.Password = Password;
            this.To = To;
            this.ID = ID;
            this.Count = Count;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListResponse", Namespace="http://www.AsreFaraErtebat.com/", Order=0)]
        public SendSMS.GetSms.ListResponseBody Body;
        
        public ListResponse() {
        }
        
        public ListResponse(SendSMS.GetSms.ListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.AsreFaraErtebat.com/")]
    public partial class ListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SendSMS.GetSms.MessageReceived[] ListResult;
        
        public ListResponseBody() {
        }
        
        public ListResponseBody(SendSMS.GetSms.MessageReceived[] ListResult) {
            this.ListResult = ListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetForwardUrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetForwardUrl", Namespace="http://www.AsreFaraErtebat.com/", Order=0)]
        public SendSMS.GetSms.GetForwardUrlRequestBody Body;
        
        public GetForwardUrlRequest() {
        }
        
        public GetForwardUrlRequest(SendSMS.GetSms.GetForwardUrlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.AsreFaraErtebat.com/")]
    public partial class GetForwardUrlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string To;
        
        public GetForwardUrlRequestBody() {
        }
        
        public GetForwardUrlRequestBody(string Username, string Password, string To) {
            this.Username = Username;
            this.Password = Password;
            this.To = To;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetForwardUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetForwardUrlResponse", Namespace="http://www.AsreFaraErtebat.com/", Order=0)]
        public SendSMS.GetSms.GetForwardUrlResponseBody Body;
        
        public GetForwardUrlResponse() {
        }
        
        public GetForwardUrlResponse(SendSMS.GetSms.GetForwardUrlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.AsreFaraErtebat.com/")]
    public partial class GetForwardUrlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetForwardUrlResult;
        
        public GetForwardUrlResponseBody() {
        }
        
        public GetForwardUrlResponseBody(string GetForwardUrlResult) {
            this.GetForwardUrlResult = GetForwardUrlResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InboxServiceSoapChannel : SendSMS.GetSms.InboxServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InboxServiceSoapClient : System.ServiceModel.ClientBase<SendSMS.GetSms.InboxServiceSoap>, SendSMS.GetSms.InboxServiceSoap {
        
        public InboxServiceSoapClient() {
        }
        
        public InboxServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InboxServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InboxServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InboxServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendSMS.GetSms.GetResponse SendSMS.GetSms.InboxServiceSoap.Get(SendSMS.GetSms.GetRequest request) {
            return base.Channel.Get(request);
        }
        
        public SendSMS.GetSms.MessageReceived Get(string Username, string Password, int ID) {
            SendSMS.GetSms.GetRequest inValue = new SendSMS.GetSms.GetRequest();
            inValue.Body = new SendSMS.GetSms.GetRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.ID = ID;
            SendSMS.GetSms.GetResponse retVal = ((SendSMS.GetSms.InboxServiceSoap)(this)).Get(inValue);
            return retVal.Body.GetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendSMS.GetSms.GetResponse> SendSMS.GetSms.InboxServiceSoap.GetAsync(SendSMS.GetSms.GetRequest request) {
            return base.Channel.GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendSMS.GetSms.GetResponse> GetAsync(string Username, string Password, int ID) {
            SendSMS.GetSms.GetRequest inValue = new SendSMS.GetSms.GetRequest();
            inValue.Body = new SendSMS.GetSms.GetRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.ID = ID;
            return ((SendSMS.GetSms.InboxServiceSoap)(this)).GetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendSMS.GetSms.GetNextResponse SendSMS.GetSms.InboxServiceSoap.GetNext(SendSMS.GetSms.GetNextRequest request) {
            return base.Channel.GetNext(request);
        }
        
        public SendSMS.GetSms.MessageReceived GetNext(string Username, string Password, string To, int ID) {
            SendSMS.GetSms.GetNextRequest inValue = new SendSMS.GetSms.GetNextRequest();
            inValue.Body = new SendSMS.GetSms.GetNextRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.To = To;
            inValue.Body.ID = ID;
            SendSMS.GetSms.GetNextResponse retVal = ((SendSMS.GetSms.InboxServiceSoap)(this)).GetNext(inValue);
            return retVal.Body.GetNextResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendSMS.GetSms.GetNextResponse> SendSMS.GetSms.InboxServiceSoap.GetNextAsync(SendSMS.GetSms.GetNextRequest request) {
            return base.Channel.GetNextAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendSMS.GetSms.GetNextResponse> GetNextAsync(string Username, string Password, string To, int ID) {
            SendSMS.GetSms.GetNextRequest inValue = new SendSMS.GetSms.GetNextRequest();
            inValue.Body = new SendSMS.GetSms.GetNextRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.To = To;
            inValue.Body.ID = ID;
            return ((SendSMS.GetSms.InboxServiceSoap)(this)).GetNextAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendSMS.GetSms.GetPeriorResponse SendSMS.GetSms.InboxServiceSoap.GetPerior(SendSMS.GetSms.GetPeriorRequest request) {
            return base.Channel.GetPerior(request);
        }
        
        public SendSMS.GetSms.MessageReceived GetPerior(string Username, string Password, string To, int ID) {
            SendSMS.GetSms.GetPeriorRequest inValue = new SendSMS.GetSms.GetPeriorRequest();
            inValue.Body = new SendSMS.GetSms.GetPeriorRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.To = To;
            inValue.Body.ID = ID;
            SendSMS.GetSms.GetPeriorResponse retVal = ((SendSMS.GetSms.InboxServiceSoap)(this)).GetPerior(inValue);
            return retVal.Body.GetPeriorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendSMS.GetSms.GetPeriorResponse> SendSMS.GetSms.InboxServiceSoap.GetPeriorAsync(SendSMS.GetSms.GetPeriorRequest request) {
            return base.Channel.GetPeriorAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendSMS.GetSms.GetPeriorResponse> GetPeriorAsync(string Username, string Password, string To, int ID) {
            SendSMS.GetSms.GetPeriorRequest inValue = new SendSMS.GetSms.GetPeriorRequest();
            inValue.Body = new SendSMS.GetSms.GetPeriorRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.To = To;
            inValue.Body.ID = ID;
            return ((SendSMS.GetSms.InboxServiceSoap)(this)).GetPeriorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendSMS.GetSms.GetFirstResponse SendSMS.GetSms.InboxServiceSoap.GetFirst(SendSMS.GetSms.GetFirstRequest request) {
            return base.Channel.GetFirst(request);
        }
        
        public SendSMS.GetSms.MessageReceived GetFirst(string Username, string Password, string To) {
            SendSMS.GetSms.GetFirstRequest inValue = new SendSMS.GetSms.GetFirstRequest();
            inValue.Body = new SendSMS.GetSms.GetFirstRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.To = To;
            SendSMS.GetSms.GetFirstResponse retVal = ((SendSMS.GetSms.InboxServiceSoap)(this)).GetFirst(inValue);
            return retVal.Body.GetFirstResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendSMS.GetSms.GetFirstResponse> SendSMS.GetSms.InboxServiceSoap.GetFirstAsync(SendSMS.GetSms.GetFirstRequest request) {
            return base.Channel.GetFirstAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendSMS.GetSms.GetFirstResponse> GetFirstAsync(string Username, string Password, string To) {
            SendSMS.GetSms.GetFirstRequest inValue = new SendSMS.GetSms.GetFirstRequest();
            inValue.Body = new SendSMS.GetSms.GetFirstRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.To = To;
            return ((SendSMS.GetSms.InboxServiceSoap)(this)).GetFirstAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendSMS.GetSms.GetLastResponse SendSMS.GetSms.InboxServiceSoap.GetLast(SendSMS.GetSms.GetLastRequest request) {
            return base.Channel.GetLast(request);
        }
        
        public SendSMS.GetSms.MessageReceived GetLast(string Username, string Password, string To) {
            SendSMS.GetSms.GetLastRequest inValue = new SendSMS.GetSms.GetLastRequest();
            inValue.Body = new SendSMS.GetSms.GetLastRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.To = To;
            SendSMS.GetSms.GetLastResponse retVal = ((SendSMS.GetSms.InboxServiceSoap)(this)).GetLast(inValue);
            return retVal.Body.GetLastResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendSMS.GetSms.GetLastResponse> SendSMS.GetSms.InboxServiceSoap.GetLastAsync(SendSMS.GetSms.GetLastRequest request) {
            return base.Channel.GetLastAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendSMS.GetSms.GetLastResponse> GetLastAsync(string Username, string Password, string To) {
            SendSMS.GetSms.GetLastRequest inValue = new SendSMS.GetSms.GetLastRequest();
            inValue.Body = new SendSMS.GetSms.GetLastRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.To = To;
            return ((SendSMS.GetSms.InboxServiceSoap)(this)).GetLastAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendSMS.GetSms.GetCountResponse SendSMS.GetSms.InboxServiceSoap.GetCount(SendSMS.GetSms.GetCountRequest request) {
            return base.Channel.GetCount(request);
        }
        
        public int GetCount(string Username, string Password, string To, int ID) {
            SendSMS.GetSms.GetCountRequest inValue = new SendSMS.GetSms.GetCountRequest();
            inValue.Body = new SendSMS.GetSms.GetCountRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.To = To;
            inValue.Body.ID = ID;
            SendSMS.GetSms.GetCountResponse retVal = ((SendSMS.GetSms.InboxServiceSoap)(this)).GetCount(inValue);
            return retVal.Body.GetCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendSMS.GetSms.GetCountResponse> SendSMS.GetSms.InboxServiceSoap.GetCountAsync(SendSMS.GetSms.GetCountRequest request) {
            return base.Channel.GetCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendSMS.GetSms.GetCountResponse> GetCountAsync(string Username, string Password, string To, int ID) {
            SendSMS.GetSms.GetCountRequest inValue = new SendSMS.GetSms.GetCountRequest();
            inValue.Body = new SendSMS.GetSms.GetCountRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.To = To;
            inValue.Body.ID = ID;
            return ((SendSMS.GetSms.InboxServiceSoap)(this)).GetCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendSMS.GetSms.ListResponse SendSMS.GetSms.InboxServiceSoap.List(SendSMS.GetSms.ListRequest request) {
            return base.Channel.List(request);
        }
        
        public SendSMS.GetSms.MessageReceived[] List(string Username, string Password, string To, int ID, int Count) {
            SendSMS.GetSms.ListRequest inValue = new SendSMS.GetSms.ListRequest();
            inValue.Body = new SendSMS.GetSms.ListRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.To = To;
            inValue.Body.ID = ID;
            inValue.Body.Count = Count;
            SendSMS.GetSms.ListResponse retVal = ((SendSMS.GetSms.InboxServiceSoap)(this)).List(inValue);
            return retVal.Body.ListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendSMS.GetSms.ListResponse> SendSMS.GetSms.InboxServiceSoap.ListAsync(SendSMS.GetSms.ListRequest request) {
            return base.Channel.ListAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendSMS.GetSms.ListResponse> ListAsync(string Username, string Password, string To, int ID, int Count) {
            SendSMS.GetSms.ListRequest inValue = new SendSMS.GetSms.ListRequest();
            inValue.Body = new SendSMS.GetSms.ListRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.To = To;
            inValue.Body.ID = ID;
            inValue.Body.Count = Count;
            return ((SendSMS.GetSms.InboxServiceSoap)(this)).ListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SendSMS.GetSms.GetForwardUrlResponse SendSMS.GetSms.InboxServiceSoap.GetForwardUrl(SendSMS.GetSms.GetForwardUrlRequest request) {
            return base.Channel.GetForwardUrl(request);
        }
        
        public string GetForwardUrl(string Username, string Password, string To) {
            SendSMS.GetSms.GetForwardUrlRequest inValue = new SendSMS.GetSms.GetForwardUrlRequest();
            inValue.Body = new SendSMS.GetSms.GetForwardUrlRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.To = To;
            SendSMS.GetSms.GetForwardUrlResponse retVal = ((SendSMS.GetSms.InboxServiceSoap)(this)).GetForwardUrl(inValue);
            return retVal.Body.GetForwardUrlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SendSMS.GetSms.GetForwardUrlResponse> SendSMS.GetSms.InboxServiceSoap.GetForwardUrlAsync(SendSMS.GetSms.GetForwardUrlRequest request) {
            return base.Channel.GetForwardUrlAsync(request);
        }
        
        public System.Threading.Tasks.Task<SendSMS.GetSms.GetForwardUrlResponse> GetForwardUrlAsync(string Username, string Password, string To) {
            SendSMS.GetSms.GetForwardUrlRequest inValue = new SendSMS.GetSms.GetForwardUrlRequest();
            inValue.Body = new SendSMS.GetSms.GetForwardUrlRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.To = To;
            return ((SendSMS.GetSms.InboxServiceSoap)(this)).GetForwardUrlAsync(inValue);
        }
    }
}
